version: "3"

services:
  app:
    container_name: image-previewer-app
    build:
      context: ./..
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres